[project]
name = "flet-calculator"
version = "1.0.0"
description = "A modern calculator built with Flet"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "flet>=0.28.0"
]

[tool.flet]
org = "com.zyperr"
product = "Flet Calculator"
company = "Zyperr"

[tool.flet.app]
path = "."

[tool.flet.android]
min_sdk_version = 24
target_sdk_version = 35
split_per_abi = false
